version: "3.3"

services:
  backend:
    container_name: backend_container
    image: dgichaba/yolo-client:v1.0.1
    ports:
      - 5000:5000
    depends_on: 
      - db
    volumes:
      - ./backend:/app
    environment:
      PORT: 5000
    networks:
      - yolo
    
  db:
    container_name: database_container
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - ./mongodb_vol:/data/db
      
  client:
    container_name: client_container
    image: dgichaba/yolo-client:v1.0.1
    tty: true
    ports:
      - 3000:3000
    stdin_open: true
    depends_on:
      - backend
    volumes:
      - ./client:/app
    networks:
      - yolo

networks:
  yolo:
  ipam:
  driver: default
  config:
  -subnet: 172.60.0.0/16

volumes:
  mongodb_vol:
