apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-backend-deployment
  labels:
    app: yolo-backend
  namespace: default
spec:
  selector:
    matchLabels:
      app: yolo-backend
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: yolo-backend
    spec:
      containers:
      - name: yolo-backend
        image: dgichaba/yolo-backend:v1.0.1
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
          - mountPath: "/tmp"
            name: yolo-backend 
      volumes:
      - name: yolo-backend
        persistentVolumeClaim:
          claimName: yolo-pvc-file-system

         