apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
spec:
  capacity:
   storage: 5Gi
  volumeMode: Filesystem
  accessModes:
   - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  hostPath:
   path: /tmp
   
  